repos:
  #- repo: https://github.com/pre-commit/mirrors-autopep8
  - repo: local
    hooks:
      - id: autopep8
        entry: autopep8 --indent-size=2 --in-place --aggressive --aggressive --recursive .
        name: autopep8
        language: system
        always_run: true
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 apps/ --indent-size=2 --select=F,E112,E113,E203,E304,E502,E702,E703,E71,E72,E731,W191,W6 --statistics -j4
        language: system
        always_run: true
        pass_filenames: false
